# False to use a flatfile sqlite save file
mysql:
    enabled: true
    host: localhost
    username: test
    password: test
    database: test
    testmode: true
#If a string has a % variable in it, it is very important to keep it in the string
# however you may move it around as you like.
messages:
    alreadyInGroup: "You are already in a group"
    notInGroup: "You are not in a group"
    joinedGroup: "Joined the group %s"
    leftGroup: "Left the group %s"
    chunkClaimed: "Claimed this chunk for %s"
    chunkUnclaimed: "Unclaimed this chunk for %s"
    chunkAlreadyClaimed: "This chunk is already claimed"
    groupAlreadyExists: "This group already exists"
    playerInvited: "Invited %s to join your group"
    playerKicked: "Kicked %s from your group"
    groupDisbanded: "Disbanded the group %s"
    confirmDisband: "Are you sure you want to disband? Type /group disband confirm"
    leaderSet: "Set %s as the new leader of %s"
    groupCreated: "Group %s created"
    leaderCantLeave: "You cannot leave your group as the leader"
    notLeader: "Only the group leader can do that"
    groupInfo: "You are in the group %s led by %s"
    cantFindPlayer: "Couldn't find that player"
    noInvite: "You don't have any pending invites"