#If a string has a % variable in it, it is very important to keep it in the string.
messageAlreadyInGroup: "You are already in a group"
messageNotInGroup: "You are not in a group"
messageJoinedGroup: "Joined the group %s"
messageClaimedChunk: "Claimed this chunk for %s"
messageUnclaimedChunk: "Unclaimed this chunk for %s"
messageLeftGroup: "Left the group %s"
messageInvitedPlayer: "Invited %s to join your group"
messageDisbandedGroup: "Disbanded group %s"
messageKickedPlayer: "Kicked %s from your group"
messageSetOwner: "Set %s as the new owner of %s"
messageCreatedGroup: "Group %s created"
messageLeaderCantLeave: "You cannot leave your group as the leader"
messageNotLeader: "Only the group leader can do that"
messageChunkAlreadyClaimed: "This chunk is already claimed"
messageGroupInfo: "You are in the group %s led by %s"